# Instructions for production

version: '3'
services:
  my-react-app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8080:80"

    environment:
      - REACT_APP_NAME=ikenna-prod
